export { default as Author } from "./Author";
export { default as BasicSection } from "./BasicSection";
export { default as Box } from "./Box";
export { default as ColoredText } from "./ColoredText";
export { default as Contact } from "./Contact";
export { default as FAQ } from "./FAQ";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as HowWorks } from "./HowWorks";
export { default as ListSection } from "./ListSection";
export { default as Pricing } from "./Pricing";
export { default as Program } from "./Program";
export { default as RequestForm } from "./RequestForm";
export { default as SEO } from "./SEO";
export { default as Reviews } from "./Reviews";
export { default as VideoPlayer } from "./VideoPlayer.js"
export { default as Loader } from "./Loader.js";
export { default as SubscribeForm } from "./SubscribeForm.js";
